"""Elasticsearch DSL query generation."""

import json
from datetime import datetime
from typing import Any, Dict, List

from purpleforge.utils.logging import get_logger

logger = get_logger(__name__)


class ElasticGenerator:
    """Generate Elasticsearch DSL queries."""

    file_extension = "elastic.json"

    def generate(
        self,
        scenario: Dict[str, Any],
        telemetry: List[Dict[str, Any]],
        correlation: Dict[str, Any],
    ) -> str:
        """
        Generate Elasticsearch queries from scenario execution.

        Args:
            scenario: Scenario definition
            telemetry: Telemetry events
            correlation: Correlation data

        Returns:
            Elasticsearch DSL queries as JSON string
        """
        logger.info("Generating Elasticsearch DSL queries")

        queries = {
            "metadata": {
                "scenario": scenario.get("name", "Unknown"),
                "generated": datetime.utcnow().isoformat() + "Z",
                "description": "Elasticsearch DSL queries generated by PurpleForge",
            },
            "queries": [],
        }

        # Generate queries based on scenario steps
        for step in scenario.get("steps", []):
            step_type = step.get("type", "")
            step_id = step.get("id", "")

            if step_type == "http_request":
                query = self._generate_http_query(step, scenario)
                if query:
                    queries["queries"].append({
                        "step_id": step_id,
                        "description": step.get("description", ""),
                        "query": query,
                    })

            elif step_type == "sql_probe":
                query = self._generate_sql_probe_query(step, scenario)
                if query:
                    queries["queries"].append({
                        "step_id": step_id,
                        "description": "SQL Injection Probe Detection",
                        "query": query,
                    })

            elif step_type == "xss_probe":
                query = self._generate_xss_probe_query(step, scenario)
                if query:
                    queries["queries"].append({
                        "step_id": step_id,
                        "description": "XSS Probe Detection",
                        "query": query,
                    })

        return json.dumps(queries, indent=2)

    def _generate_http_query(
        self, step: Dict[str, Any], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Elasticsearch query for HTTP request."""
        params = step.get("parameters", {})
        method = params.get("method", "GET")
        path = params.get("path", "/")

        return {
            "query": {
                "bool": {
                    "must": [
                        {"match": {"http.request.method": method}},
                        {"wildcard": {"url.path": f"*{path}*"}},
                    ]
                }
            }
        }

    def _generate_sql_probe_query(
        self, step: Dict[str, Any], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Elasticsearch query for SQL injection probe."""
        return {
            "query": {
                "bool": {
                    "should": [
                        {"wildcard": {"url.query": "*'*"}},
                        {"wildcard": {"url.query": "*--*"}},
                        {"wildcard": {"url.query": "*OR 1=1*"}},
                        {"wildcard": {"url.query": "*UNION SELECT*"}},
                        {"wildcard": {"url.query": "*admin'--*"}},
                    ],
                    "minimum_should_match": 1,
                }
            },
            "aggs": {
                "by_source_ip": {
                    "terms": {
                        "field": "source.ip",
                        "size": 10,
                    }
                }
            },
        }

    def _generate_xss_probe_query(
        self, step: Dict[str, Any], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Elasticsearch query for XSS probe."""
        return {
            "query": {
                "bool": {
                    "should": [
                        {"wildcard": {"url.query": "*<script>*"}},
                        {"wildcard": {"url.query": "*javascript:*"}},
                        {"wildcard": {"url.query": "*onerror=*"}},
                        {"wildcard": {"url.query": "*alert(*"}},
                    ],
                    "minimum_should_match": 1,
                }
            },
            "aggs": {
                "by_source_ip": {
                    "terms": {
                        "field": "source.ip",
                        "size": 10,
                    }
                }
            },
        }
