"""Sigma rule generation."""

import uuid
from datetime import datetime
from typing import Any, Dict, List

import yaml

from purpleforge.utils.logging import get_logger

logger = get_logger(__name__)


class SigmaGenerator:
    """Generate Sigma detection rules."""

    file_extension = "sigma.yml"

    def generate(
        self,
        scenario: Dict[str, Any],
        telemetry: List[Dict[str, Any]],
        correlation: Dict[str, Any],
    ) -> str:
        """
        Generate Sigma rules from scenario execution.

        Args:
            scenario: Scenario definition
            telemetry: Telemetry events
            correlation: Correlation data

        Returns:
            Sigma rules as YAML string
        """
        logger.info("Generating Sigma rules")

        rules = []

        # Generate rules based on scenario steps
        for step in scenario.get("steps", []):
            step_type = step.get("type", "")
            step_id = step.get("id", "")

            # Find relevant telemetry for this step
            step_events = [
                e for e in telemetry if e.get("step_id") == step_id
            ]

            if step_type in ("http_request", "http_get_baseline"):
                rule = self._generate_http_rule(step, step_events, scenario)
                if rule:
                    rules.append(rule)

            elif step_type in ("sql_probe", "sqli_error_probe_safe"):
                rule = self._generate_sql_probe_rule(step, step_events, scenario)
                if rule:
                    rules.append(rule)

            elif step_type in ("xss_probe", "reflected_xss_probe_safe"):
                rule = self._generate_xss_probe_rule(step, step_events, scenario)
                if rule:
                    rules.append(rule)

            elif step_type == "header_analysis":
                rule = self._generate_header_analysis_rule(step, step_events, scenario)
                if rule:
                    rules.append(rule)

        # Convert rules to YAML
        output = "# Sigma Detection Rules Generated by PurpleForge\n"
        output += f"# Scenario: {scenario.get('name', 'Unknown')}\n"
        output += f"# Generated: {datetime.utcnow().isoformat()}Z\n\n"

        for i, rule in enumerate(rules):
            if i > 0:
                output += "\n---\n\n"
            output += yaml.dump(rule, default_flow_style=False, sort_keys=False)

        return output

    def _generate_http_rule(
        self, step: Dict[str, Any], events: List[Dict[str, Any]], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Sigma rule for HTTP request."""
        params = step.get("parameters", {})
        method = params.get("method", "GET")
        path = params.get("path", "/")

        return {
            "title": f"PurpleForge - HTTP {method} Request to {path}",
            "id": str(uuid.uuid4()),
            "status": "experimental",
            "description": f"Detects HTTP {method} request to {path} from PurpleForge scenario",
            "references": [
                f"PurpleForge Step ID: {step.get('id')}",
            ],
            "author": "PurpleForge",
            "date": datetime.utcnow().strftime("%Y/%m/%d"),
            "logsource": {
                "category": "webserver",
            },
            "detection": {
                "selection": {
                    "cs-method": method,
                    "cs-uri-stem|contains": path,
                },
                "condition": "selection",
            },
            "falsepositives": [
                "Legitimate HTTP requests to the same endpoint",
            ],
            "level": "low",
            "tags": self._get_attack_tags(scenario),
        }

    def _generate_sql_probe_rule(
        self, step: Dict[str, Any], events: List[Dict[str, Any]], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Sigma rule for SQL injection probe."""
        return {
            "title": "PurpleForge - SQL Injection Probe Detected",
            "id": str(uuid.uuid4()),
            "status": "experimental",
            "description": "Detects SQL injection probe patterns from PurpleForge scenario",
            "references": [
                "https://attack.mitre.org/techniques/T1190/",
                f"PurpleForge Step ID: {step.get('id')}",
            ],
            "author": "PurpleForge",
            "date": datetime.utcnow().strftime("%Y/%m/%d"),
            "logsource": {
                "category": "webserver",
                "product": "apache",
            },
            "detection": {
                "selection": {
                    "cs-uri-query|contains": [
                        "'",
                        "--",
                        "OR 1=1",
                        "UNION SELECT",
                        "' OR '1'='1",
                        "admin'--",
                        "' OR 1=1--",
                    ],
                },
                "condition": "selection",
            },
            "falsepositives": [
                "Legitimate use of special characters in URLs",
                "Security testing activities",
            ],
            "level": "medium",
            "tags": self._get_attack_tags(scenario) + ["attack.initial_access", "attack.t1190"],
        }

    def _generate_xss_probe_rule(
        self, step: Dict[str, Any], events: List[Dict[str, Any]], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Sigma rule for XSS probe."""
        return {
            "title": "PurpleForge - XSS Probe Detected",
            "id": str(uuid.uuid4()),
            "status": "experimental",
            "description": "Detects Cross-Site Scripting (XSS) probe patterns from PurpleForge scenario",
            "references": [
                "https://attack.mitre.org/techniques/T1059/",
                f"PurpleForge Step ID: {step.get('id')}",
            ],
            "author": "PurpleForge",
            "date": datetime.utcnow().strftime("%Y/%m/%d"),
            "logsource": {
                "category": "webserver",
            },
            "detection": {
                "selection": {
                    "cs-uri-query|contains": [
                        "<script>",
                        "javascript:",
                        "onerror=",
                        "onload=",
                        "<img src=x",
                        "alert(",
                    ],
                },
                "condition": "selection",
            },
            "falsepositives": [
                "Legitimate JavaScript in query parameters",
                "Security testing activities",
            ],
            "level": "medium",
            "tags": self._get_attack_tags(scenario),
        }

    def _generate_header_analysis_rule(
        self, step: Dict[str, Any], events: List[Dict[str, Any]], scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate Sigma rule for suspicious header analysis."""
        return {
            "title": "PurpleForge - Security Header Analysis Scan",
            "id": str(uuid.uuid4()),
            "status": "experimental",
            "description": "Detects security header analysis and reconnaissance activity",
            "references": [
                "https://attack.mitre.org/techniques/T1595/",
                f"PurpleForge Step ID: {step.get('id')}",
            ],
            "author": "PurpleForge",
            "date": datetime.utcnow().strftime("%Y/%m/%d"),
            "logsource": {
                "category": "webserver",
            },
            "detection": {
                "selection": {
                    "cs-method": "OPTIONS",
                },
                "condition": "selection",
            },
            "falsepositives": [
                "Legitimate CORS preflight requests",
                "Browser-initiated OPTIONS requests",
            ],
            "level": "low",
            "tags": self._get_attack_tags(scenario) + ["attack.reconnaissance", "attack.t1595"],
        }

    def _get_attack_tags(self, scenario: Dict[str, Any]) -> List[str]:
        """Extract ATT&CK tags from scenario."""
        tags = []
        for technique in scenario.get("att_ck_techniques", []):
            tags.append(f"attack.{technique.lower()}")
        return tags
