"""Snort/Suricata rule generation."""

from datetime import datetime
from typing import Any, Dict, List

from purpleforge.utils.logging import get_logger

logger = get_logger(__name__)


class SnortGenerator:
    """Generate Snort/Suricata rules."""

    file_extension = "rules"

    def generate(
        self,
        scenario: Dict[str, Any],
        telemetry: List[Dict[str, Any]],
        correlation: Dict[str, Any],
    ) -> str:
        """
        Generate Snort rules from scenario execution.

        Args:
            scenario: Scenario definition
            telemetry: Telemetry events
            correlation: Correlation data

        Returns:
            Snort rules as string
        """
        logger.info("Generating Snort/Suricata rules")

        rules = []

        # Header
        rules.append("# Snort/Suricata Rules Generated by PurpleForge")
        rules.append(f"# Scenario: {scenario.get('name', 'Unknown')}")
        rules.append(f"# Generated: {datetime.utcnow().isoformat()}Z")
        rules.append("#")
        rules.append("# Usage: Add these rules to your Snort/Suricata rules directory")
        rules.append("")

        sid_base = 1000000  # Starting SID for PurpleForge rules

        # Generate rules based on scenario steps
        for i, step in enumerate(scenario.get("steps", []), 1):
            step_type = step.get("type", "")

            if step_type == "http_request":
                rule = self._generate_http_rule(step, scenario, sid_base + i)
                if rule:
                    rules.append(f"# Step: {step.get('id')} - {step.get('description', '')}")
                    rules.append(rule)
                    rules.append("")

            elif step_type == "sql_probe":
                rule = self._generate_sql_probe_rule(step, scenario, sid_base + i)
                if rule:
                    rules.append(f"# Step: {step.get('id')} - SQL Injection Probe")
                    rules.append(rule)
                    rules.append("")

            elif step_type == "xss_probe":
                rule = self._generate_xss_probe_rule(step, scenario, sid_base + i)
                if rule:
                    rules.append(f"# Step: {step.get('id')} - XSS Probe")
                    rules.append(rule)
                    rules.append("")

        # Add generic web attack detection rules
        rules.append("# Generic Web Attack Detection")
        rules.append(self._generate_generic_sqli_rule(sid_base + 900))
        rules.append("")
        rules.append(self._generate_generic_xss_rule(sid_base + 901))
        rules.append("")

        return "\n".join(rules)

    def _generate_http_rule(
        self, step: Dict[str, Any], scenario: Dict[str, Any], sid: int
    ) -> str:
        """Generate Snort rule for HTTP request."""
        params = step.get("parameters", {})
        method = params.get("method", "GET")
        path = params.get("path", "/")

        return (
            f'alert tcp any any -> any any '
            f'(msg:"PurpleForge: HTTP {method} to {path}"; '
            f'flow:to_server,established; '
            f'content:"{method}"; http_method; '
            f'content:"{path}"; http_uri; '
            f'classtype:web-application-activity; '
            f'sid:{sid}; rev:1;)'
        )

    def _generate_sql_probe_rule(
        self, step: Dict[str, Any], scenario: Dict[str, Any], sid: int
    ) -> str:
        """Generate Snort rule for SQL injection probe."""
        pcre = r"/('|--|union.*select|or.*1=1)/i"
        return (
            f'alert tcp any any -> any any '
            f'(msg:"PurpleForge: SQL Injection Probe Detected"; '
            f'flow:to_server,established; '
            f'content:"GET"; http_method; '
            f'pcre:"{pcre}"; '
            f'classtype:web-application-attack; '
            f'sid:{sid}; rev:1;)'
        )

    def _generate_xss_probe_rule(
        self, step: Dict[str, Any], scenario: Dict[str, Any], sid: int
    ) -> str:
        """Generate Snort rule for XSS probe."""
        pcre = r"/(<script|javascript:|onerror=|alert\()/i"
        return (
            f'alert tcp any any -> any any '
            f'(msg:"PurpleForge: XSS Probe Detected"; '
            f'flow:to_server,established; '
            f'content:"GET"; http_method; '
            f'pcre:"{pcre}"; '
            f'classtype:web-application-attack; '
            f'sid:{sid}; rev:1;)'
        )

    def _generate_generic_sqli_rule(self, sid: int) -> str:
        """Generate generic SQL injection detection rule."""
        pcre = r"/('.*or.*'|'.*union.*select|'.*and.*1=1|admin'--)/i"
        return (
            f'alert tcp any any -> any any '
            f'(msg:"PurpleForge: Generic SQL Injection Attempt"; '
            f'flow:to_server,established; '
            f'pcre:"{pcre}"; '
            f'classtype:web-application-attack; '
            f'sid:{sid}; rev:1;)'
        )

    def _generate_generic_xss_rule(self, sid: int) -> str:
        """Generate generic XSS detection rule."""
        pcre = r"/(<script.*>|javascript:.*alert|onerror=.*alert)/i"
        return (
            f'alert tcp any any -> any any '
            f'(msg:"PurpleForge: Generic XSS Attempt"; '
            f'flow:to_server,established; '
            f'pcre:"{pcre}"; '
            f'classtype:web-application-attack; '
            f'sid:{sid}; rev:1;)'
        )
