"""Splunk SPL query generation."""

from datetime import datetime
from typing import Any, Dict, List

from purpleforge.utils.logging import get_logger

logger = get_logger(__name__)


class SplunkGenerator:
    """Generate Splunk SPL queries."""

    file_extension = "splunk.spl"

    def generate(
        self,
        scenario: Dict[str, Any],
        telemetry: List[Dict[str, Any]],
        correlation: Dict[str, Any],
    ) -> str:
        """
        Generate Splunk queries from scenario execution.

        Args:
            scenario: Scenario definition
            telemetry: Telemetry events
            correlation: Correlation data

        Returns:
            Splunk SPL queries as string
        """
        logger.info("Generating Splunk SPL queries")

        queries = []

        # Header
        queries.append("# Splunk SPL Queries Generated by PurpleForge")
        queries.append(f"# Scenario: {scenario.get('name', 'Unknown')}")
        queries.append(f"# Generated: {datetime.utcnow().isoformat()}Z")
        queries.append("")

        # Generate queries based on scenario steps
        for step in scenario.get("steps", []):
            step_type = step.get("type", "")
            step_id = step.get("id", "")

            if step_type == "http_request":
                query = self._generate_http_query(step, scenario)
                if query:
                    queries.append(f"## Step: {step_id} - {step.get('description', '')}")
                    queries.append(query)
                    queries.append("")

            elif step_type == "sql_probe":
                query = self._generate_sql_probe_query(step, scenario)
                if query:
                    queries.append(f"## Step: {step_id} - SQL Injection Probe")
                    queries.append(query)
                    queries.append("")

            elif step_type == "xss_probe":
                query = self._generate_xss_probe_query(step, scenario)
                if query:
                    queries.append(f"## Step: {step_id} - XSS Probe")
                    queries.append(query)
                    queries.append("")

        return "\n".join(queries)

    def _generate_http_query(
        self, step: Dict[str, Any], scenario: Dict[str, Any]
    ) -> str:
        """Generate Splunk query for HTTP request."""
        params = step.get("parameters", {})
        method = params.get("method", "GET")
        path = params.get("path", "/")

        return f'''index=web sourcetype=access_combined
| search method="{method}" uri_path="*{path}*"
| stats count by src_ip, method, uri_path, status
| where count > 1'''

    def _generate_sql_probe_query(
        self, step: Dict[str, Any], scenario: Dict[str, Any]
    ) -> str:
        """Generate Splunk query for SQL injection probe."""
        return '''index=web sourcetype=access_combined
| search uri_query IN ("*'*", "*--*", "*OR 1=1*", "*UNION SELECT*", "*admin'--*")
| stats count by src_ip, uri_path, uri_query, status
| where count > 0
| eval severity="medium"
| table _time, src_ip, uri_path, uri_query, status, severity'''

    def _generate_xss_probe_query(
        self, step: Dict[str, Any], scenario: Dict[str, Any]
    ) -> str:
        """Generate Splunk query for XSS probe."""
        return '''index=web sourcetype=access_combined
| search uri_query IN ("*<script>*", "*javascript:*", "*onerror=*", "*alert(*")
| stats count by src_ip, uri_path, uri_query, status
| where count > 0
| eval severity="medium"
| table _time, src_ip, uri_path, uri_query, status, severity'''
