"""YARA rule generation for artifacts."""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from purpleforge.utils.logging import get_logger

logger = get_logger(__name__)


class YaraGenerator:
    """Generate YARA rules for artifacts."""

    file_extension = "yara"

    def generate(
        self,
        scenario: Dict[str, Any],
        telemetry: List[Dict[str, Any]],
        correlation: Dict[str, Any],
    ) -> str:
        """
        Generate YARA rules from scenario artifacts.

        Args:
            scenario: Scenario definition
            telemetry: Telemetry events
            correlation: Correlation data

        Returns:
            YARA rules as string
        """
        logger.info("Generating YARA rules")

        rules = []

        # Header
        rules.append("/*")
        rules.append("   YARA Rules Generated by PurpleForge")
        rules.append(f"   Scenario: {scenario.get('name', 'Unknown')}")
        rules.append(f"   Generated: {datetime.utcnow().isoformat()}Z")
        rules.append("*/")
        rules.append("")

        # Generate rules for web artifacts
        if scenario.get("category") == "web":
            rules.append(self._generate_web_artifact_rule(scenario, telemetry))

        # Generate rules for binary artifacts (if applicable)
        if scenario.get("category") == "binary":
            rules.append(self._generate_binary_artifact_rule(scenario, telemetry))

        # Generic suspicious patterns rule
        rules.append(self._generate_suspicious_patterns_rule(scenario))

        return "\n".join(rules)

    def _generate_web_artifact_rule(
        self, scenario: Dict[str, Any], telemetry: List[Dict[str, Any]]
    ) -> str:
        """Generate YARA rule for web artifacts."""
        scenario_name = scenario.get("name", "Unknown").replace(" ", "_")

        rule = f'''rule PurpleForge_Web_{scenario_name}
{{
    meta:
        description = "Detects artifacts from PurpleForge web scenario"
        author = "PurpleForge"
        date = "{datetime.utcnow().strftime("%Y-%m-%d")}"
        scenario = "{scenario.get('name', 'Unknown')}"

    strings:
        $sql1 = "' OR '1'='1" nocase
        $sql2 = "UNION SELECT" nocase
        $sql3 = "admin'--" nocase
        $xss1 = "<script>alert(" nocase
        $xss2 = "javascript:alert(" nocase
        $xss3 = "onerror=" nocase
        $traversal1 = "../../../" nocase
        $cmd1 = ";whoami" nocase
        $cmd2 = "|cat /etc/passwd" nocase

    condition:
        any of ($sql*, $xss*, $traversal*, $cmd*)
}}'''
        return rule

    def _generate_binary_artifact_rule(
        self, scenario: Dict[str, Any], telemetry: List[Dict[str, Any]]
    ) -> str:
        """Generate YARA rule for binary artifacts."""
        scenario_name = scenario.get("name", "Unknown").replace(" ", "_")

        rule = f'''rule PurpleForge_Binary_{scenario_name}
{{
    meta:
        description = "Detects binary artifacts from PurpleForge scenario"
        author = "PurpleForge"
        date = "{datetime.utcnow().strftime("%Y-%m-%d")}"
        scenario = "{scenario.get('name', 'Unknown')}"

    strings:
        $mz = "MZ"
        $pe = "PE"
        $suspicious1 = "cmd.exe" wide ascii
        $suspicious2 = "powershell.exe" wide ascii
        $suspicious3 = "WScript.Shell" wide ascii

    condition:
        uint16(0) == 0x5A4D and any of ($suspicious*)
}}'''
        return rule

    def _generate_suspicious_patterns_rule(self, scenario: Dict[str, Any]) -> str:
        """Generate generic suspicious patterns rule."""
        rule = f'''rule PurpleForge_Suspicious_Patterns
{{
    meta:
        description = "Detects suspicious patterns related to PurpleForge scenario"
        author = "PurpleForge"
        date = "{datetime.utcnow().strftime("%Y-%m-%d")}"

    strings:
        // Network indicators
        $ip1 = /\\d{{1,3}}\\.\\d{{1,3}}\\.\\d{{1,3}}\\.\\d{{1,3}}:4444/
        $ip2 = /\\d{{1,3}}\\.\\d{{1,3}}\\.\\d{{1,3}}\\.\\d{{1,3}}:8888/

        // Common attack strings
        $attack1 = "nc -e /bin/sh" nocase
        $attack2 = "bash -i >& /dev/tcp/" nocase
        $attack3 = "powershell -enc" nocase
        $attack4 = "wget http://" nocase
        $attack5 = "curl http://" nocase

        // Base64 encoded common commands
        $b64_1 = "Y21kLmV4ZQ==" // cmd.exe
        $b64_2 = "cG93ZXJzaGVsbA==" // powershell

    condition:
        any of them
}}'''
        return rule
